### ISSUE TITLE
Change License to CC

### ISSUE THREAD

**Issue by Zorziel** [Zorziel/Orangueen#4]
I think the main repository's license should be changed to CC-BY instead of MIT.  Allows more compatibility with licenses from other apps that will use the theme.

**Comment by girijakar** [comment]
Most of the CC licenses have good compatibility when remixing work under different licenses. So, if you are sure to change the license then do it. But you can't change the license for the current release, you can change it for future releases.

If you want to change it then try [this](https://stackoverflow.com/a/20243295) once.

**Comment by Zorziel** [comment]
> you can't change the license for the current release, you can change it for future releases

Thank you @girijakar, that was my understanding as well.  I'm going to release the current version as 0.1 with the existing license and then do a PR for a new license for future versions.

**Comment by girijakar** [comment]
You're welcome.
Let me know if I can help you with anything else.

P.S. I am a newbie, still learning stuff. So, I can help you with some minor changes related to documentation or something like that. If there are some issues with the code, I'll try my best to resolve those.
